# Generated by Django 4.2 on 2023-05-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0004_remove_address_user"),
        ("users", "0002_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="addresses.address",
            ),
        ),
    ]
