# Generated by Django 4.2 on 2023-05-05 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0005_cart_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
    ]
