# Generated by Django 4.2 on 2023-05-06 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_initial"),
        ("carts", "0006_remove_cart_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to="products.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
