# Generated by Django 4.2 on 2023-05-06 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0011_remove_cart_products_alter_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproducts",
            name="storage",
        ),
    ]
