# Generated by Django 4.2 on 2023-05-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pedido Realizado', 'Order Received'), ('Em Andamento', 'On Going'), ('Entregue', 'Complete'), ('Não Informado', 'Not Informed')], default='Não Informado', max_length=30)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_orders', to='carts.cart')),
            ],
        ),
    ]
