# Generated by Django 4.2 on 2023-05-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_vendor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pedido Realizado", "Order Received"),
                    ("Em Andamento", "On Going"),
                    ("Entregue", "Complete"),
                ],
                default="Pedido Realizado",
                max_length=30,
            ),
        ),
    ]
