# Generated by Django 4.2 on 2023-05-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_remove_order_cart_order_cart_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart_products",
            field=models.JSONField(default={}),
        ),
    ]
